### ISSUE TITLE
How to do NER using ProDepDet

### ISSUE THREAD

**Issue by katouHui** [KUAS-ubicomp-lab/ProDepDet#1]
Hello, I have read your paper and it is very inspiring. I would like to apply your task to the task of ner. After a few days of trying, I have found that this is not a very simple thing. I am not sure how to modify it specifically. I would like to ask you to provide some suggestions. Thank you

**Comment by CyraxSector** [comment]
Hello, thanks for reaching out. This framework is specially designed for out-of-domain tasks transfer. In order to use ProDepDet for NER, you have to come up with the respective prompt template, prompt verbalizer, and set of demonstrations (if any) for the NER task which you are trying out. Depending on the NER task, I think you may need to use an ontological mapping based on the knowledge base (KB) you are using. You may use your proposing prompt verbalizer as the KB to make your life easy. The best place to start your analysis would be OntoPrompt, ontology-enhanced prompt-tuning (https://dl.acm.org/doi/abs/10.1145/3485447.3511921). Hope this helps!!!

**Comment by katouHui** [comment]
> Hello, thanks for reaching out. This framework is specially designed for out-of-domain tasks transfer. In order to use ProDepDet for NER, you have to come up with the respective prompt template, prompt verbalizer, and set of demonstrations (if any) for the NER task which you are trying out. Depending on the NER task, I think you may need to use an ontological mapping based on the knowledge base (KB) you are using. You may use your proposing prompt verbalizer as the KB to make your life easy. The best place to start your analysis would be OntoPrompt, ontology-enhanced prompt-tuning ([https://dl.acm.org/doi/abs/10.1145/3485447.3511921[ ](https://www.sci-hub.ee/10.1145/3485447.3511921)](https://dl.acm.org/doi/abs/10.1145/3485447.3511921)). Hope this helps!!!

Thank you very much for your reply. Thank you for your suggestions and giving me some new ideas. I am also looking forward to your future work
